server:
    port: 443
    metrics: 8095
    # Set to true if you've a LB in front of RTCStats and you are obtaining
    # its IP address as part of the X-Forwarded-For header
    skipLoadBalancerIp: false
    logLevel: info
    jsonConsoleLog: false
    # The provided certificates are intended for local testing using a HTTPS server
    useHTTPS: false
    keyPath: './certs/key.pem'
    certPath: './certs/cert.pem'
    tempPath : 'temp'
    appEnvironment: dev

features:
    disableFeatExtraction: false

amplitude:
    key:

s3:
    accessKeyId:
    secretAccessKey:
    region: 'us-west-2'
    bucket: 'jitsi-pilot-rtcstats-server'
    useIAMAuth: false,
    # Default value is 2 days
    signedLinkExpirationSec: 172800

firehose:
    accessKeyId:
    secretAccessKey:
    region:
    meetingStatsStream:
    pcStatsStream:
    trackStatsStream:
    e2ePingStream:
    faceLandmarksStream:
    meetingEventStream:

gcp:
    bucket:
    dataset:
    table:
    maxFlushTime:
    bufferSize:

github:
    client_id: GITHUB_CLIENT_ID
    client_secret: GITHUB_SECRET
    callback_url: GITHUB_CALLBACK_URL

dynamo:
  tableName:
  endpoint:

webhooks:
    apiEndpoint: https://api-vo.jitsi.net/vpaas-event-acceptor/v1/forward
    sendRtcstatsUploaded: true
    jwtAudience: jitsi-meet
    jwtIssuer: meetings.8x8
    # JWT Expiration defaults to 2h
    jwtTTLSec: 7200

secretmanager:
    region: us-west-2
    jwtSecretId: jitsi-micros/props/auth-jwt
